---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Make sure cache directory exists
      file:
        path: "{{ vagrant_home }}/cache/{{ ansible_distribution }}/{{ ansible_distribution_version }}/"
        state: directory

- hosts: master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  tasks:
  - name: Pull GlusterFS Docker image
    command: docker pull gluster/gluster-centos:latest
    register: task_result
    until: task_result.rc == 0
    retries: 5
    delay: 1

  - name: Pull heketi Docker image
    command: docker pull heketi/heketi:dev
    register: task_result
    until: task_result.rc == 0
    retries: 5
    delay: 1

  - name: Archive Docker cache
    shell: 'docker save $(docker images --format {% raw %}{{.Repository}}{% endraw %}) | gzip -N > /tmp/docker-images.tgz'
    when: false

  # NOTE: The 'become' line below is a workaround for this: https://github.com/ansible/ansible/issues/11702#issuecomment-224918570
  - name: Copy Docker cache to host
    fetch:
      src: "/tmp/docker-images.tgz"
      dest: "{{ vagrant_home }}/cache/{{ ansible_distribution }}/{{ ansible_distribution_version }}/"
      flat: true
    become: false
